name = "koreader-sync2"
main = "src/index.ts"
compatibility_date = "2026-03-25"

[vars]
SESSION_TTL_HOURS = "168"

[[d1_databases]]
binding = "DB"
database_name = "koreader-sync-db2"
database_id = "b952dc95-c423-4710-a087-f236136730df"
migrations_dir = "migrations"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
